"""extract submission_ai_insights table

Revision ID: 98be13f8321e
Revises: 0ef6a9b9508f
Create Date: 2026-09-25 22:10:20.480096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98be13f8321e'
down_revision: Union[str, Sequence[str], None] = '0ef6a9b9508f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_ai_insights',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'in_progress'"), nullable=False),
    sa.Column('suggested_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_grade', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('improvements', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('item_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.drop_column('submissions', 'ai_insights')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('ai_insights', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('submission_ai_insights')
    # ### end Alembic commands ###
