"""optimize_indexes_for_submissions_and_assignments

Revision ID: eca08cabf466
Revises: 98be13f8321e
Create Date: 2026-09-26 17:52:43.151913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca08cabf466'
down_revision: Union[str, Sequence[str], None] = '98be13f8321e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_assignments_class'), table_name='assignments')
    op.create_index('idx_assignments_classroom_created', 'assignments', ['classroom_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_submissions_student_status', 'submissions', ['student_id', 'status', sa.literal_column('submitted_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_submissions_student_status', table_name='submissions')
    op.drop_index('idx_assignments_classroom_created', table_name='assignments')
    op.create_index(op.f('idx_assignments_class'), 'assignments', ['classroom_id'], unique=False)
    # ### end Alembic commands ###
